FROM ruby:3.2

# (Optionally install system dependencies like node, yarn, postgresql-client, etc.)
RUN apt-get update && apt-get install -y nodejs yarn build-essential ruby-dev

WORKDIR /usr/src/app
COPY Gemfile Gemfile.lock ./

RUN bundle install

# Copy all source — this is where your Rails app lives
COPY . .

# Expose app port + debugger ports for RubyMine
EXPOSE 3000 1234 26162

COPY entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
CMD ["rails", "server", "-b", "0.0.0.0"]
