development:
  adapter: redis
  url: <%= ENV.fetch("CABLE_REDIS_URL", "redis://#{ENV.fetch('REDIS_HOST', 'parrots-redis')}:#{ENV.fetch('REDIS_PORT', '6379')}/1") %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("CABLE_REDIS_URL", "redis://#{ENV.fetch('REDIS_HOST', 'parrots-redis')}:#{ENV.fetch('REDIS_PORT', '6379')}/1") %>
  channel_prefix: app_production

